/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as UniversityMatcherRouteImport } from './routes/university-matcher'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as ExplorerPresentRouteImport } from './routes/explorer_.present'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityMatcherRoute = UniversityMatcherRouteImport.update({
  id: '/university-matcher',
  path: '/university-matcher',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerPresentRoute = ExplorerPresentRouteImport.update({
  id: '/explorer_/present',
  path: '/explorer/present',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/assessment': typeof AssessmentRoute
  '/courses': typeof CoursesRoute
  '/documents': typeof DocumentsRoute
  '/explorer': typeof ExplorerRoute
  '/follow-ups': typeof FollowUpsRoute
  '/payments': typeof PaymentsRoute
  '/pipelines': typeof PipelinesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/universities': typeof UniversitiesRoute
  '/university-matcher': typeof UniversityMatcherRoute
  '/visa': typeof VisaRoute
  '/explorer/present': typeof ExplorerPresentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/assessment': typeof AssessmentRoute
  '/courses': typeof CoursesRoute
  '/documents': typeof DocumentsRoute
  '/explorer': typeof ExplorerRoute
  '/follow-ups': typeof FollowUpsRoute
  '/payments': typeof PaymentsRoute
  '/pipelines': typeof PipelinesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/universities': typeof UniversitiesRoute
  '/university-matcher': typeof UniversityMatcherRoute
  '/visa': typeof VisaRoute
  '/explorer/present': typeof ExplorerPresentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/assessment': typeof AssessmentRoute
  '/courses': typeof CoursesRoute
  '/documents': typeof DocumentsRoute
  '/explorer': typeof ExplorerRoute
  '/follow-ups': typeof FollowUpsRoute
  '/payments': typeof PaymentsRoute
  '/pipelines': typeof PipelinesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/universities': typeof UniversitiesRoute
  '/university-matcher': typeof UniversityMatcherRoute
  '/visa': typeof VisaRoute
  '/explorer_/present': typeof ExplorerPresentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/assessment'
    | '/courses'
    | '/documents'
    | '/explorer'
    | '/follow-ups'
    | '/payments'
    | '/pipelines'
    | '/reports'
    | '/settings'
    | '/students'
    | '/universities'
    | '/university-matcher'
    | '/visa'
    | '/explorer/present'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/assessment'
    | '/courses'
    | '/documents'
    | '/explorer'
    | '/follow-ups'
    | '/payments'
    | '/pipelines'
    | '/reports'
    | '/settings'
    | '/students'
    | '/universities'
    | '/university-matcher'
    | '/visa'
    | '/explorer/present'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/assessment'
    | '/courses'
    | '/documents'
    | '/explorer'
    | '/follow-ups'
    | '/payments'
    | '/pipelines'
    | '/reports'
    | '/settings'
    | '/students'
    | '/universities'
    | '/university-matcher'
    | '/visa'
    | '/explorer_/present'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AssessmentRoute: typeof AssessmentRoute
  CoursesRoute: typeof CoursesRoute
  DocumentsRoute: typeof DocumentsRoute
  ExplorerRoute: typeof ExplorerRoute
  FollowUpsRoute: typeof FollowUpsRoute
  PaymentsRoute: typeof PaymentsRoute
  PipelinesRoute: typeof PipelinesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRoute
  UniversitiesRoute: typeof UniversitiesRoute
  UniversityMatcherRoute: typeof UniversityMatcherRoute
  VisaRoute: typeof VisaRoute
  ExplorerPresentRoute: typeof ExplorerPresentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university-matcher': {
      id: '/university-matcher'
      path: '/university-matcher'
      fullPath: '/university-matcher'
      preLoaderRoute: typeof UniversityMatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer_/present': {
      id: '/explorer_/present'
      path: '/explorer/present'
      fullPath: '/explorer/present'
      preLoaderRoute: typeof ExplorerPresentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AssessmentRoute: AssessmentRoute,
  CoursesRoute: CoursesRoute,
  DocumentsRoute: DocumentsRoute,
  ExplorerRoute: ExplorerRoute,
  FollowUpsRoute: FollowUpsRoute,
  PaymentsRoute: PaymentsRoute,
  PipelinesRoute: PipelinesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRoute,
  UniversitiesRoute: UniversitiesRoute,
  UniversityMatcherRoute: UniversityMatcherRoute,
  VisaRoute: VisaRoute,
  ExplorerPresentRoute: ExplorerPresentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
